#!/bin/bash

# andpack: A script to decompile/recompile Android apk packages

# Copyright (C) 2012 Nathan Campos
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Variables
pass=mypass						# Your keystore password
kalias=myalias					# Your keystore alias
keyst=my-release-key.keystore	# Your keystore location

function decompile()
{
    local apk=$1 # APK filename
    if [ ! $(echo $apk | grep -e '.apk') ]; then
        local apk="$apk.apk"
    fi
    echo "You chose to decompile $apk"
    echo "* You will need root privileges *"

    if sudo apktool d $apk
    then
        echo "$apk sucessfully decompiled"
    else
        echo "ERROR: Failed to decompile $apk" >&2; exit -1;
    fi
}

function compile()
{
    local apk=$1.apk # APK filename
    local unmodapk=$1.unmodifyed.apk # Unmodified APK filename
    echo "You chose to compile $1"
    echo "Renaming the unmodifyed APK to $unmodapk"
    mv $apk $unmodapk || exit -1
    
    echo "* You will need root privileges *"

    if sudo apktool b $1 $apk
    then
        echo "$apk sucessfully built"
        echo "Setting 777 permission to $apk"
        sudo chmod 777 $apk

        echo "Signing $apk"
        if jarsigner -verbose -keystore $keyst -storepass $pass $apk $kalias
        then
            echo "$apk signed sucessfully"
        else
            echo "ERROR: Failed to sign $apk. Please recheck the variables" >&2; exit -1;
        fi
        if [ $installapk ]; then
            echo "Uninstalling the existing application from your phone..."
            if adb uninstall $1
            then
                echo "The application has been found and nuked"
            else
                echo "ERROR: Could not uninstall or could not locate the application" >&2; exit -1;
            fi

            echo "Installing the new application"
            if adb install $apk
            then
                echo "All Done"
            else
                echo "ERROR: Could not install the application" >&2; exit -1;
            fi
        fi
    else
        echo "Something went wrong" >&2; exit -1;
    fi
}

while getopts ':d:b:k:p:i' opt; do
    case $opt in
        d) $decomapk=$OPTARG;;
        b) $compdir=$OPTARG;;
        k) keyst=$OPTARG;;
        p) pass=$OPTARGS;;
        a) kalias=$OPTARGS;;
        i) installapk=true;;
        \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
        :) echo "Option -$OPTARG requires an argument." >&2; exit 1;;
    esac
done

if [ $decomapk ]; then
    decompile $decomapk
fi

if [ $compdir ]; then
    compile $compdir
fi

