#!/bin/bash

# adb_global: A script to allow global access of the ADB executable provided with the Android SDK http://developer.android.com/sdk/index.html

# Copyright (C) 2012  Ryan Esteves
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
function helpmsg
{
	echo ""
	echo "Usage: $0 [ARGUMENTS] <PathToAdb>"
	echo "	Arguments"
	echo "		-h -H	Creates a symbolic link in the users bin folder (~/bin/) rather than using the global PATH variable"
	echo ""
}
function addpathvar
{
	ADBLOC=$1
	read -p "This is going to modify the .bashrc file in your home folder. Continue? (Y,n)" yn
	case $yn in
		[Nn]* ) exit;;
    	esac
	echo 'export PATH=$PATH:'$ADBLOC >> ~/.bashrc
	echo "Done! You should now restart your computer."
}
function createsymlink
{
	ADBLOC=$1/adb
	if [ ! -d ~/bin/ ]; then
		mkdir -p ~/bin/
	fi
	if [ -e $ADBLOC ]; then
		ln -s $ADBLOC ~/bin/
		echo "Done!"
	else
		echo "Invalid ADB location specified! File does not exist!"
		exit 1
	fi
}
if [ ! $1 ]; then
helpmsg
exit
fi

if [ $1 == "-h" ]; then
	if [ $2 ]; then
		echo "Create Symbolic link"
		ADBLOC=$(dirname "$2")
		if [ -d $ADBLOC ]; then
			createsymlink $ADBLOC
		else
			echo "Invalid path or argument: $2"
			helpmsg
		fi
	else
		helpmsg
		exit 1
	fi
else
	echo "Add to PATH"
	ADBLOC=$(dirname "$1")
	if [ -d $ADBLOC ]; then
		addpathvar $ADBLOC
	else
		echo "Invalid path or argument: $1"
		helpmsg
		exit 1
	fi
fi
